# Generated by Django 5.2 on 2025-05-01 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_colorvariant_sizevariiant_product_color_variant_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SizeVariiant',
            new_name='SizeVariant',
        ),
    ]
